[gdrive]
type = drive
scope = drive.readonly
token = {"access_token":"ya29.a0ARGnu0ahPd27R26WSKhavPEtZDkMNppotEcScSGNFMTBismGEjdQNxQRIccXWl3kSh6fLZMx_rkdot9g3uEbMU7ZnhiA-gXDH7RfBJz-XBAnM-n7XyoBOt31iuCa0rpe706ntB1LnRNyYdClWexyusi1tEohrBMpbdwpgg3lAt7OJ-RXkFpa1cngSJcgFDRpSSYky67caCgYKAe4SARYSFQHGX2MijYEqYgKqg-NptHU7PAhYRw0207","token_type":"Bearer","refresh_token":"1//0gXzcAv_-Nes2CgYIARAAGBASNwF-L9IrCNKjTJK8HsjF77BAhgsxFHC8EQmK169cjshYZuBwZfVrJKdD8F3Tp2ghuO1dvGkydoA","expiry":"2026-08-01T10:53:12.546565505Z"}
team_drive = 
client_id = 792881715920-fvasuf40afoo484dht8enc1ad5oalclh.apps.googleusercontent.com
client_secret = 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

